package jframe;


import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import java.sql.PreparedStatement;



/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author BALA JI
 */
public class Cancellation extends javax.swing.JFrame {

    /**
     * Creates new form cons
     */
    public Cancellation() {
        initComponents();
        GetTicket();
        FcodeTb.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        TIdCb = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        BookBtn = new javax.swing.JButton();
        ResetBtn = new javax.swing.JButton();
        BackBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        CancellationTable = new javax.swing.JTable();
        FcodeTb = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        CDate = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(204, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 0, 51));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1550, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 23, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1550, -1));

        jLabel8.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 0, 0));
        jLabel8.setText("Cancellation list");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 310, -1, -1));

        jLabel11.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 22)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 0, 0));
        jLabel11.setText("Flight Code");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 130, -1, 38));

        jLabel14.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 27)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 0, 0));
        jLabel14.setText("AIR LINE BILLING SYSTEM");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 30, -1, -1));

        TIdCb.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        TIdCb.setForeground(new java.awt.Color(255, 0, 0));
        TIdCb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TIdCbActionPerformed(evt);
            }
        });
        jPanel3.add(TIdCb, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 180, 180, 35));

        jLabel12.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 0, 0));
        jLabel12.setText("Ticket Cancellation");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 80, -1, -1));

        BookBtn.setBackground(new java.awt.Color(242, 242, 242));
        BookBtn.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 22)); // NOI18N
        BookBtn.setForeground(new java.awt.Color(255, 0, 0));
        BookBtn.setText("Cancel");
        BookBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BookBtnMouseClicked(evt);
            }
        });
        jPanel3.add(BookBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 250, 112, -1));

        ResetBtn.setBackground(new java.awt.Color(242, 242, 242));
        ResetBtn.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 22)); // NOI18N
        ResetBtn.setForeground(new java.awt.Color(255, 0, 0));
        ResetBtn.setText("Reset");
        ResetBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ResetBtnMouseClicked(evt);
            }
        });
        jPanel3.add(ResetBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 250, 93, -1));

        BackBtn.setBackground(new java.awt.Color(242, 242, 242));
        BackBtn.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 22)); // NOI18N
        BackBtn.setForeground(new java.awt.Color(255, 0, 0));
        BackBtn.setText("Back");
        BackBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackBtnMouseClicked(evt);
            }
        });
        jPanel3.add(BackBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 250, 122, -1));

        CancellationTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(CancellationTable);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, 1430, 410));

        FcodeTb.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 22)); // NOI18N
        FcodeTb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FcodeTbActionPerformed(evt);
            }
        });
        jPanel3.add(FcodeTb, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 180, 200, -1));

        jLabel17.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 22)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 0, 0));
        jLabel17.setText("Ticket Id");
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 130, -1, -1));

        jLabel13.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 22)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 0, 0));
        jLabel13.setText("Flight Date");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 130, -1, 38));

        CDate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CDateMouseClicked(evt);
            }
        });
        jPanel3.add(CDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 180, 180, 30));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1550, 810));

        setSize(new java.awt.Dimension(1561, 809));
    }// </editor-fold>//GEN-END:initComponents

    private void TIdCbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TIdCbActionPerformed
        GetFCode();
    }//GEN-LAST:event_TIdCbActionPerformed

    private void FcodeTbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FcodeTbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FcodeTbActionPerformed

    private void BackBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackBtnMouseClicked
        new MainForm().setVisible(true);
   this.dispose();
   
    }//GEN-LAST:event_BackBtnMouseClicked
    Connection Con = null;
    PreparedStatement pst = null;
    ResultSet Rs = null,Rsl = null;
    Statement St = null,Stl = null;  
    private void GetTicket() 
    { 
        try {
            Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/airline","root","");
            St = Con.createStatement();
            String Query = "select * from booking_tbl";
            Rs = St.executeQuery(Query);
            while(Rs.next())
            {
                String T = Rs.getString("ticket_id");
                TIdCb.addItem(T);
            }
        
        } catch (Exception e) {
        }
        
    }
    private void GetFCode()
    {
        String Query = "select * from booking_tbl where ticket_id ="+TIdCb.getSelectedItem().toString();
        Statement St;
        java.sql.ResultSet Rs;
        try {
            Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/airline","root","");
            St = Con.createStatement();
            Rs = St.executeQuery(Query);
            if(Rs.next())
            {
                FcodeTb.setText(Rs.getString("fl_code"));
                
            }
        } catch (Exception e) {
        }
    }
       private void DisplayCan()
            
    {
        try {
            Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/airline","root","");
            St = Con.createStatement();
            Rs = St.executeQuery("select * from cancell_tbl");
            CancellationTable.setModel(net.proteanit.sql.DbUtils.resultSetToTableModel(Rs));
            
        } catch (Exception e) {
        }
        
    }
    int CId = 0;
    private void CountCanc()
    {
        try {
            Stl = Con.createStatement();
            Rsl = Stl.executeQuery("select Max(can_id) from cancell_tbl");
            Rsl.next();
            CId = Rsl.getInt(1)+1;
        } catch (Exception e) {
        }
    }
      
    private void ResetBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ResetBtnMouseClicked
       FcodeTb.setText("");
    }//GEN-LAST:event_ResetBtnMouseClicked
private void Cancel()
{
    try {
                Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/airline","root","");
                String Query = "Delete from booking_tbl where ticket_id="+TIdCb.getSelectedIndex();
                Statement Del = Con.createStatement();
                Del.executeUpdate(Query);
                //JOptionPane.showMessageDialog(this, "Flight Deleted");
               // DisplayFlight();
               } catch (Exception e) {
                   JOptionPane.showMessageDialog(this, e);
            }
}
    private void BookBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BookBtnMouseClicked
          if(FcodeTb.getText().isEmpty()) 
        {
          JOptionPane.showMessageDialog(this, "Missing Information");  
        }else{
            try{
                CountCanc();
                Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/airline","root","");
                //PreparedStatement Add = Con.prepareStatement("insert into CancellationTbl values(?,?,?,?)");
                String sql = "insert into cancell_tbl(can_id,ticket_id,fl_code,fl_date) values(?,?,?,?)";
                java.sql.PreparedStatement Add = Con.prepareStatement(sql);
                Add.setInt(1, CId);
                Add.setInt(2, Integer.valueOf(TIdCb.getSelectedItem().toString()));
                Add.setString(3, FcodeTb.getText());
                Add.setString(4, CDate.getDate().toString());
                int row = Add.executeUpdate();
                JOptionPane.showMessageDialog(this, "Ticket Cancelled");
               Con.close();
               Cancel();
                DisplayCan();
                //Clear();
            }catch(Exception e){
            JOptionPane.showMessageDialog(this,e);
            }
        }
    }//GEN-LAST:event_BookBtnMouseClicked

    private void CDateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CDateMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_CDateMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cancellation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cancellation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cancellation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cancellation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cancellation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackBtn;
    private javax.swing.JButton BookBtn;
    private com.toedter.calendar.JDateChooser CDate;
    private javax.swing.JTable CancellationTable;
    private javax.swing.JTextField FcodeTb;
    private javax.swing.JButton ResetBtn;
    private javax.swing.JComboBox<String> TIdCb;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
