package jframe;


import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import javax.swing.JOptionPane;
import java.sql.PreparedStatement;
import javax.swing.table.DefaultTableModel;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author BALA JI
 */
public class Flights extends javax.swing.JFrame {

    /**
     * Creates new form flights
     */
    public Flights() {
        initComponents();
        DisplayFlight();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rSDateChooserBeanInfo1 = new rojeru_san.componentes.RSDateChooserBeanInfo();
        rSDateChooserBeanInfo2 = new rojeru_san.componentes.RSDateChooserBeanInfo();
        rSDateChooserBeanInfo3 = new rojeru_san.componentes.RSDateChooserBeanInfo();
        rSDateChooserBeanInfo4 = new rojeru_san.componentes.RSDateChooserBeanInfo();
        rSDateChooserBeanInfo5 = new rojeru_san.componentes.RSDateChooserBeanInfo();
        rSDateChooserBeanInfo6 = new rojeru_san.componentes.RSDateChooserBeanInfo();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        SeatsTb = new javax.swing.JTextField();
        FSourceCb = new javax.swing.JComboBox<>();
        FDestCb = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        BackBtn = new javax.swing.JButton();
        SaveBtn = new javax.swing.JButton();
        EditBtn = new javax.swing.JButton();
        DeleteBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        FlightsTable = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        FDate = new com.toedter.calendar.JDateChooser();
        FCodeTb = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 153));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 0, 51));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1601, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 23, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1601, -1));

        jLabel8.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 0, 0));
        jLabel8.setText("Fligths list");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 320, -1, -1));

        jLabel9.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 22)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 0, 0));
        jLabel9.setText("Fligth code");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, 149, -1));

        jLabel10.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 22)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 0, 0));
        jLabel10.setText("Number of Seats");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 150, -1, -1));

        jLabel11.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 22)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 0, 0));
        jLabel11.setText("Source");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 150, -1, -1));

        jLabel13.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 22)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 0, 0));
        jLabel13.setText("Destination");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 150, -1, -1));

        jLabel14.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 27)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 0, 0));
        jLabel14.setText("AIR LINE BILLING SYSTEM");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 30, -1, -1));

        SeatsTb.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 22)); // NOI18N
        SeatsTb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeatsTbActionPerformed(evt);
            }
        });
        jPanel3.add(SeatsTb, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 190, 203, -1));

        FSourceCb.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        FSourceCb.setForeground(new java.awt.Color(255, 0, 0));
        FSourceCb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mumbai", "Delhi", "Chainnai", "Goa", "Tamilnadu", "Banglore", " " }));
        jPanel3.add(FSourceCb, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 190, 129, 32));

        FDestCb.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        FDestCb.setForeground(new java.awt.Color(255, 0, 0));
        FDestCb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mumbai", "Delhi", "Tamilnadu", "Ajmair", "Goa", "India", "Maharashtra" }));
        FDestCb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FDestCbActionPerformed(evt);
            }
        });
        jPanel3.add(FDestCb, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 190, 141, 35));

        jLabel12.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 0, 0));
        jLabel12.setText("Manage Fligths");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 80, -1, -1));

        BackBtn.setBackground(new java.awt.Color(242, 242, 242));
        BackBtn.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 22)); // NOI18N
        BackBtn.setForeground(new java.awt.Color(255, 0, 0));
        BackBtn.setText("Back");
        BackBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackBtnMouseClicked(evt);
            }
        });
        jPanel3.add(BackBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 260, 122, -1));

        SaveBtn.setBackground(new java.awt.Color(242, 242, 242));
        SaveBtn.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 22)); // NOI18N
        SaveBtn.setForeground(new java.awt.Color(255, 0, 0));
        SaveBtn.setText("Save");
        SaveBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SaveBtnMouseClicked(evt);
            }
        });
        jPanel3.add(SaveBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 260, 93, -1));

        EditBtn.setBackground(new java.awt.Color(242, 242, 242));
        EditBtn.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 22)); // NOI18N
        EditBtn.setForeground(new java.awt.Color(255, 0, 0));
        EditBtn.setText("Edit");
        EditBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EditBtnMouseClicked(evt);
            }
        });
        jPanel3.add(EditBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 260, 93, -1));

        DeleteBtn.setBackground(new java.awt.Color(242, 242, 242));
        DeleteBtn.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 22)); // NOI18N
        DeleteBtn.setForeground(new java.awt.Color(255, 0, 0));
        DeleteBtn.setText("Delete");
        DeleteBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DeleteBtnMouseClicked(evt);
            }
        });
        jPanel3.add(DeleteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 260, 122, -1));

        FlightsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        FlightsTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FlightsTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(FlightsTable);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 1480, 440));

        jLabel15.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 22)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 0, 0));
        jLabel15.setText("Tickets of Date");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 150, 183, -1));

        FDate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FDateMouseClicked(evt);
            }
        });
        jPanel3.add(FDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 190, 159, 37));

        FCodeTb.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 22)); // NOI18N
        FCodeTb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FCodeTbActionPerformed(evt);
            }
        });
        jPanel3.add(FCodeTb, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, 167, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1690, 870));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1695, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SaveBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SaveBtnMouseClicked
        if(FCodeTb.getText().isEmpty() || SeatsTb.getText().isEmpty() || FSourceCb.getSelectedIndex() == -1 || FDestCb.getSelectedIndex() == -1)
        {
            JOptionPane.showMessageDialog(this, "Missing Information");
        }else{
            try{
                Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/airline","root","");
                String sql = "insert into flight_tbl(fl_code,fl_source,fl_dest,fl_date,fl_seats) values(?,?,?,?,?)";
                PreparedStatement Add = Con.prepareStatement(sql);
                Add.setString(1, FCodeTb.getText());
                Add.setString(2, FSourceCb.getSelectedItem().toString());
                Add.setString(3, FDestCb.getSelectedItem().toString());
                Add.setString(4, FDate.getDate().toString());
                Add.setInt(5, Integer.valueOf(SeatsTb.getText()));
                    int row = Add.executeUpdate();
                    JOptionPane.showMessageDialog(this, "Flight Added");
                    Con.close();
                    DisplayFlight();
                    Clear();
                }catch(Exception e){
                    JOptionPane.showMessageDialog(this,e);
                }
            }

    }//GEN-LAST:event_SaveBtnMouseClicked

    private void BackBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackBtnMouseClicked
        new MainForm().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BackBtnMouseClicked

    private void FDestCbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FDestCbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FDestCbActionPerformed

    private void SeatsTbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeatsTbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SeatsTbActionPerformed

    private void DeleteBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteBtnMouseClicked
       if (Key == "") {
            JOptionPane.showMessageDialog(this, "select a Flight");
        }else{
            try {
                Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/airline","root","");
                String Query = "Delete from flight_tbl where fl_code='"+Key+"'";
                Statement Del = Con.createStatement();
                Del.executeUpdate(Query);
                JOptionPane.showMessageDialog(this, "Flight Deleted");
                DisplayFlight();
               } catch (Exception e) {
                   JOptionPane.showMessageDialog(this, e);
            }
            
       }
    }//GEN-LAST:event_DeleteBtnMouseClicked
 String Key = "";
    private void FlightsTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FlightsTableMouseClicked
  DefaultTableModel model = (DefaultTableModel)FlightsTable.getModel();
      int MyIndex = FlightsTable.getSelectedRow();
      Key = model.getValueAt(MyIndex, 0).toString();
      FSourceCb.setSelectedItem(model.getValueAt(MyIndex, 1).toString());
      FDestCb.setSelectedItem(model.getValueAt(MyIndex, 2).toString());
      SeatsTb.setText(model.getValueAt(MyIndex, 3).toString());
      
    }//GEN-LAST:event_FlightsTableMouseClicked

    private void EditBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditBtnMouseClicked
        if(Key == "")
        {
          JOptionPane.showMessageDialog(this, "select A Flight");  
        }else{
            try{
                //CountPassengers();
                Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/airline","root","");
                String Query = "update flight_tbl set fl_source = ?, fl_dest = ?,fl_date=?,fl_seats=? where fl_code=?";
                PreparedStatement Add = Con.prepareStatement(Query);
                Add.setString(5, Key);
                Add.setString(1, FSourceCb.getSelectedItem().toString());
                Add.setString(2, FDestCb.getSelectedItem().toString());
                Add.setString(3, FDate.getDate().toString());
                Add.setString(4, SeatsTb.getText());
                int row = Add.executeUpdate();
                JOptionPane.showMessageDialog(this, "Flight Updated");
               Con.close();
                DisplayFlight();
                Clear();
            }catch(Exception e){
            JOptionPane.showMessageDialog(this,e);
            }
        }
                
                                       

    }//GEN-LAST:event_EditBtnMouseClicked

    private void FDateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FDateMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_FDateMouseClicked

    private void FCodeTbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FCodeTbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FCodeTbActionPerformed
Connection Con = null;
    java.sql.PreparedStatement pst = null;
    java.sql.ResultSet Rs = null,Rsl = null;
    Statement St = null,Stl = null; 
    private void DisplayFlight()
            
    {
        try {
            Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/airline","root","");
            St = Con.createStatement();
            Rs = St.executeQuery("select * from flight_tbl");
           FlightsTable.setModel(net.proteanit.sql.DbUtils.resultSetToTableModel(Rs));
            
        } catch (Exception e) {
        }
        
    }
      private void Clear()
    {
        FCodeTb.setText("");
        SeatsTb.setText("");
     }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Flights.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Flights.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Flights.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Flights.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Flights().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackBtn;
    private javax.swing.JButton DeleteBtn;
    private javax.swing.JButton EditBtn;
    private javax.swing.JTextField FCodeTb;
    private com.toedter.calendar.JDateChooser FDate;
    private javax.swing.JComboBox<String> FDestCb;
    private javax.swing.JComboBox<String> FSourceCb;
    private javax.swing.JTable FlightsTable;
    private javax.swing.JButton SaveBtn;
    private javax.swing.JTextField SeatsTb;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private rojeru_san.componentes.RSDateChooserBeanInfo rSDateChooserBeanInfo1;
    private rojeru_san.componentes.RSDateChooserBeanInfo rSDateChooserBeanInfo2;
    private rojeru_san.componentes.RSDateChooserBeanInfo rSDateChooserBeanInfo3;
    private rojeru_san.componentes.RSDateChooserBeanInfo rSDateChooserBeanInfo4;
    private rojeru_san.componentes.RSDateChooserBeanInfo rSDateChooserBeanInfo5;
    private rojeru_san.componentes.RSDateChooserBeanInfo rSDateChooserBeanInfo6;
    // End of variables declaration//GEN-END:variables
}
